#!/usr/bin/env python3
"""Incrementally update the offline A-share OHLCV dataset after market close.

The script updates an existing offline directory in the same schema generated by
``generate_offline_a_share_data.py``:

    date,symbol,open,high,low,close,volume,amount,turnover

It is designed for the daily workflow:

1. Keep the existing universe by default.
2. Re-fetch a short recent window for each symbol, not only one date. This
   protects the dataset from missing trading days and small front-adjustment
   changes.
3. Merge by (date, symbol), preserving leading zeros.
4. Rebuild ``prices_long.csv`` from per-symbol files.
"""

from __future__ import annotations

import argparse
import fcntl
import json
import logging
import os
import tempfile
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Iterator

import pandas as pd
import requests

from generate_offline_a_share_data import RUNTIME_COLUMNS, to_runtime_ohlcv
from stock_feature_pipeline import (
    fetch_daily_history,
    get_a_share_universe,
    is_bse,
    is_chinext,
    is_star_market,
    normalize_symbol,
)


LOGGER = logging.getLogger("offline_a_share_daily_update")
DEFAULT_SCHEDULER_STATE_FILE = Path("run/offline_daily_update_scheduler_state.json")


def yyyymmdd(value: pd.Timestamp) -> str:
    return value.strftime("%Y%m%d")


def iso_date(value: str | pd.Timestamp) -> str:
    return pd.to_datetime(value).strftime("%Y-%m-%d")


def parse_sources(value: str) -> tuple[str, ...]:
    return tuple(source.strip().lower() for source in value.split(",") if source.strip())


def read_csv_strict(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, dtype={"symbol": str})


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
            tmp_path = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path and tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def atomic_write_json(path: Path, payload: dict) -> None:
    atomic_write_text(path, json.dumps(payload, ensure_ascii=False, indent=2))


def load_json_file(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        LOGGER.warning("Failed to read JSON state %s: %s", path, exc)
        return {}


def update_scheduler_state(path: Path, *, target_date: str, status: str) -> None:
    state = load_json_file(path)
    state.update(
        {
            "last_run_date": target_date,
            "last_status": status,
            "updated_at": datetime.now().isoformat(timespec="seconds"),
        }
    )
    atomic_write_json(path, state)


def atomic_write_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="", dir=path.parent, delete=False) as handle:
            tmp_path = Path(handle.name)
            df.to_csv(handle, index=False)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    finally:
        if tmp_path and tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def setup_logging(level: str, log_file: str | None = None) -> None:
    handlers: list[logging.Handler] = [logging.StreamHandler()]
    if log_file:
        log_path = Path(log_file).expanduser()
        log_path.parent.mkdir(parents=True, exist_ok=True)
        handlers.append(logging.FileHandler(log_path, encoding="utf-8"))
    logging.basicConfig(
        level=getattr(logging, level),
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=handlers,
        force=True,
    )


@contextmanager
def exclusive_lock(lock_file: Path, stale_seconds: int = 6 * 3600) -> Iterator[bool]:
    """Acquire a non-blocking file lock; return False if another run is active."""
    lock_file.parent.mkdir(parents=True, exist_ok=True)
    handle = lock_file.open("a+", encoding="utf-8")
    try:
        try:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            try:
                handle.seek(0)
                payload = json.loads(handle.read() or "{}")
                started_at = pd.to_datetime(payload.get("started_at"), errors="coerce")
                if pd.notna(started_at):
                    age = (pd.Timestamp.now() - started_at).total_seconds()
                    LOGGER.warning("Another updater is running; lock age %.0fs at %s", age, lock_file)
                    if age > stale_seconds:
                        LOGGER.error("Lock is stale by age, but OS lock is still held; skip to avoid corruption.")
                else:
                    LOGGER.warning("Another updater is running; lock file=%s", lock_file)
            except Exception:  # noqa: BLE001
                LOGGER.warning("Another updater is running; lock file=%s", lock_file)
            yield False
            return

        handle.seek(0)
        handle.truncate()
        handle.write(
            json.dumps(
                {
                    "pid": os.getpid(),
                    "started_at": datetime.now().isoformat(timespec="seconds"),
                },
                ensure_ascii=False,
            )
        )
        handle.flush()
        yield True
    finally:
        try:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
        finally:
            handle.close()


def run_alert(command: str | None, *, status: str, message: str, output_dir: Path) -> None:
    if not command:
        return
    env = os.environ.copy()
    env.update(
        {
            "UPDATE_STATUS": status,
            "UPDATE_MESSAGE": message,
            "UPDATE_OUTPUT_DIR": str(output_dir),
        }
    )
    try:
        subprocess.run(command, shell=True, check=False, env=env, timeout=60)
    except Exception as exc:  # noqa: BLE001
        LOGGER.error("Failed to run alert command: %s", exc)


def load_feishu_webhooks(path: str | None) -> list[str]:
    if not path:
        return []
    webhook_path = Path(path).expanduser()
    if not webhook_path.exists():
        LOGGER.warning("Feishu webhook file does not exist: %s", webhook_path)
        return []
    content = webhook_path.read_text(encoding="utf-8")
    webhooks: list[str] = []
    for raw in content.replace(",", "\n").splitlines():
        webhook = raw.strip().strip("`").strip().strip('"').strip("'")
        if not webhook or webhook.startswith("#"):
            continue
        webhooks.append(webhook)
    deduped = list(dict.fromkeys(webhooks))
    if not deduped:
        LOGGER.warning("Feishu webhook file is empty: %s", webhook_path)
    return deduped


def load_feishu_webhook(path: str | None) -> str | None:
    webhooks = load_feishu_webhooks(path)
    return webhooks[0] if webhooks else None


def send_to_feishu(webhook_url: str, content: str, timeout: int = 10) -> bool:
    payload = {
        "msg_type": "text",
        "content": {"text": content},
    }
    try:
        response = requests.post(webhook_url, json=payload, timeout=timeout)
        response.raise_for_status()
        data = response.json()
    except Exception as exc:  # noqa: BLE001
        LOGGER.error("Failed to send Feishu notification: %s", exc)
        return False

    code = data.get("code")
    if code not in {0, None}:
        LOGGER.error("Feishu notification returned non-zero response: %s", data)
        return False
    LOGGER.info("Feishu notification sent.")
    return True


def send_to_feishu_all(webhook_urls: list[str], content: str, timeout: int = 10) -> bool:
    if not webhook_urls:
        return False
    results = [send_to_feishu(webhook, content, timeout=timeout) for webhook in webhook_urls]
    LOGGER.info("Feishu notifications sent: %s/%s", sum(bool(item) for item in results), len(results))
    return all(results)


def build_feishu_message(summary: dict, output_dir: Path, *, title: str = "A股离线数据每日更新") -> str:
    status = summary.get("status", "unknown")
    status_text = {
        "success": "成功",
        "failed": "失败",
        "skipped_non_trading_day": "跳过：非交易日",
        "skipped_locked": "跳过：已有任务运行",
    }.get(status, str(status))
    combined = summary.get("combined") or {}
    lines = [
        f"{title}：{status_text}",
        f"日期：{summary.get('end_date', '-')}",
        f"目录：{output_dir}",
        f"新增：{summary.get('updated', 0)}，刷新：{summary.get('refreshed', 0)}，无数据：{summary.get('no_new', 0)}，失败：{summary.get('failed', 0)}",
        f"失败率：{float(summary.get('failed_ratio', 0.0)):.2%}",
    ]
    if combined:
        lines.extend(
            [
                f"prices_long：{combined.get('start_date', '-')} 至 {combined.get('end_date', '-')}",
                f"覆盖股票数：{combined.get('symbols', '-')}",
                f"总行数：{combined.get('rows', '-')}",
            ]
        )
    return "\n".join(lines)


def notify_feishu(args: argparse.Namespace, summary: dict, *, title: str = "A股离线数据每日更新") -> None:
    if not args.feishu_notify:
        return
    if args.dry_run and not args.feishu_notify_dry_run:
        LOGGER.info("Skip Feishu notification for dry-run.")
        return
    webhooks = load_feishu_webhooks(args.feishu_webhook_file)
    if not webhooks:
        return
    send_to_feishu_all(webhooks, build_feishu_message(summary, Path(args.output_dir), title=title))


def load_existing_universe(output_dir: Path) -> pd.DataFrame:
    path = output_dir / "universe.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing universe.csv: {path}")
    universe = read_csv_strict(path)
    if "symbol" not in universe.columns:
        raise ValueError(f"universe.csv must contain a symbol column: {path}")
    universe["symbol"] = universe["symbol"].map(normalize_symbol)
    return universe.drop_duplicates("symbol").sort_values("symbol").reset_index(drop=True)


def refresh_universe(
    *,
    output_dir: Path,
    date: str,
    data_sources: tuple[str, ...],
    include_chinext: bool,
    include_star: bool,
    include_bse: bool,
    include_st: bool,
    limit: int | None,
) -> pd.DataFrame:
    universe_source = "jqdata" if "jqdata" in data_sources else "akshare"
    universe = get_a_share_universe(
        exclude_chinext=not include_chinext,
        exclude_star=not include_star,
        exclude_bse=not include_bse,
        exclude_st=not include_st,
        source=universe_source,
        date=date,
    ).copy()
    universe["symbol"] = universe["symbol"].map(normalize_symbol)
    if not include_chinext:
        universe = universe[~universe["symbol"].map(is_chinext)]
    if not include_star:
        universe = universe[~universe["symbol"].map(is_star_market)]
    if not include_bse:
        universe = universe[~universe["symbol"].map(is_bse)]
    universe = universe.drop_duplicates("symbol").sort_values("symbol").reset_index(drop=True)
    if limit:
        universe = universe.head(limit)
    atomic_write_csv(universe, output_dir / "universe.csv")
    return universe


def is_trading_day(end_date: str, data_sources: tuple[str, ...], adjust: str, mode: str) -> bool:
    """Return whether end_date should be treated as an A-share trading day."""
    date = pd.to_datetime(end_date)
    if mode == "off":
        return True
    if date.weekday() >= 5:
        return False
    if mode == "weekday":
        return True

    # Auto mode: a weekday holiday is skipped if a liquid benchmark has no bar.
    # This uses the same data path as the updater and avoids adding calendar deps.
    benchmark = "000001"
    try:
        history = fetch_daily_history(
            symbol=benchmark,
            start_date=yyyymmdd(date),
            end_date=yyyymmdd(date),
            adjust=adjust,
            data_sources=data_sources,
        )
    except Exception as exc:  # noqa: BLE001
        LOGGER.warning("Trading-day check failed for %s: %s", end_date, exc)
        return False
    if history.empty:
        return False
    dates = set(pd.to_datetime(history["trade_date"], errors="coerce").dt.strftime("%Y%m%d").dropna())
    return yyyymmdd(date) in dates


def latest_symbol_date(symbol_path: Path) -> pd.Timestamp | None:
    if not symbol_path.exists():
        return None
    try:
        df = pd.read_csv(symbol_path, usecols=["date"], dtype={"date": str})
    except Exception as exc:  # noqa: BLE001
        LOGGER.warning("Failed to read existing dates from %s: %s", symbol_path, exc)
        return None
    if df.empty:
        return None
    return pd.to_datetime(df["date"], errors="coerce").max()


def merge_symbol_frame(existing_path: Path, update_df: pd.DataFrame, trim_before: str | None) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    if existing_path.exists():
        existing = read_csv_strict(existing_path)
        frames.append(existing)
    if not update_df.empty:
        frames.append(update_df)
    if not frames:
        return pd.DataFrame(columns=RUNTIME_COLUMNS)

    merged = pd.concat(frames, ignore_index=True)
    merged["symbol"] = merged["symbol"].map(normalize_symbol)
    merged["date"] = pd.to_datetime(merged["date"], errors="coerce").dt.strftime("%Y-%m-%d")
    for col in RUNTIME_COLUMNS:
        if col not in merged.columns:
            merged[col] = pd.NA
    numeric_cols = [col for col in RUNTIME_COLUMNS if col not in {"date", "symbol"}]
    for col in numeric_cols:
        merged[col] = pd.to_numeric(merged[col], errors="coerce")
    merged = merged.dropna(subset=["date", "symbol", "close"])
    if trim_before:
        trim = iso_date(trim_before)
        merged = merged[merged["date"] >= trim]
    merged = (
        merged[RUNTIME_COLUMNS]
        .sort_values(["date", "symbol"])
        .drop_duplicates(["date", "symbol"], keep="last")
        .reset_index(drop=True)
    )
    return merged


def update_symbol(
    *,
    symbol: str,
    symbol_dir: Path,
    end_date: str,
    refresh_days: int,
    adjust: str,
    data_sources: tuple[str, ...],
    trim_before: str | None,
    dry_run: bool,
) -> dict:
    symbol = normalize_symbol(symbol)
    path = symbol_dir / f"{symbol}.csv"
    latest = latest_symbol_date(path)
    end_ts = pd.to_datetime(end_date)
    if latest is None:
        start_ts = end_ts - pd.Timedelta(days=max(refresh_days, 30))
        previous_end = None
    else:
        start_ts = latest - pd.Timedelta(days=max(refresh_days, 0))
        previous_end = latest.strftime("%Y-%m-%d")

    if start_ts > end_ts:
        return {
            "symbol": symbol,
            "status": "up_to_date",
            "previous_end_date": previous_end,
            "new_end_date": previous_end,
            "added_rows": 0,
            "rows": None,
            "path": str(path),
        }

    history = fetch_daily_history(
        symbol=symbol,
        start_date=yyyymmdd(start_ts),
        end_date=yyyymmdd(end_ts),
        adjust=adjust,
        data_sources=data_sources,
    )
    update_df = to_runtime_ohlcv(history, symbol)
    if update_df.empty:
        return {
            "symbol": symbol,
            "status": "no_new_data",
            "previous_end_date": previous_end,
            "new_end_date": previous_end,
            "added_rows": 0,
            "rows": None,
            "path": str(path),
        }

    before_dates: set[str] = set()
    if path.exists():
        before = pd.read_csv(path, usecols=["date"], dtype={"date": str})
        before_dates = set(pd.to_datetime(before["date"]).dt.strftime("%Y-%m-%d"))

    merged = merge_symbol_frame(path, update_df, trim_before)
    after_dates = set(merged["date"].astype(str))
    added_rows = len(after_dates - before_dates)
    new_end = str(merged["date"].max()) if not merged.empty else previous_end
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_csv(merged, path)

    return {
        "symbol": symbol,
        "status": "updated" if added_rows > 0 else "refreshed",
        "previous_end_date": previous_end,
        "new_end_date": new_end,
        "added_rows": int(added_rows),
        "rows": int(len(merged)),
        "path": str(path),
    }


def update_symbol_with_retries(
    *,
    index: int,
    total: int,
    symbol: str,
    symbol_dir: Path,
    args: argparse.Namespace,
    data_sources: tuple[str, ...],
) -> dict:
    record: dict | None = None
    for attempt in range(1, args.retries + 2):
        try:
            LOGGER.info("[%s/%s] Update %s attempt=%s", index, total, symbol, attempt)
            record = update_symbol(
                symbol=symbol,
                symbol_dir=symbol_dir,
                end_date=args.end_date,
                refresh_days=args.refresh_days,
                adjust=args.adjust,
                data_sources=data_sources,
                trim_before=args.trim_before,
                dry_run=args.dry_run,
            )
            break
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Failed attempt %s for %s: %s", attempt, symbol, exc)
            if attempt <= args.retries:
                time.sleep(args.retry_sleep_seconds)
            else:
                LOGGER.exception("Failed to update %s after retries", symbol)
                record = {
                    "symbol": symbol,
                    "status": "failed",
                    "error": str(exc),
                    "added_rows": 0,
                    "rows": None,
                    "path": str(symbol_dir / f"{symbol}.csv"),
                }
    if args.sleep_seconds > 0:
        time.sleep(args.sleep_seconds)
    return {"index": index, **(record or {"symbol": symbol, "status": "failed", "added_rows": 0})}


def rebuild_prices_long(output_dir: Path) -> dict:
    symbol_dir = output_dir / "symbols"
    frames: list[pd.DataFrame] = []
    files = sorted(symbol_dir.glob("*.csv"))
    for path in files:
        try:
            df = read_csv_strict(path)
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Skip unreadable symbol file %s: %s", path, exc)
            continue
        if df.empty:
            continue
        df["symbol"] = df["symbol"].map(normalize_symbol)
        frames.append(df)
    if not frames:
        raise RuntimeError(f"No symbol CSV files found under {symbol_dir}")
    combined = pd.concat(frames, ignore_index=True)
    for col in RUNTIME_COLUMNS:
        if col not in combined.columns:
            combined[col] = pd.NA
    combined["date"] = pd.to_datetime(combined["date"], errors="coerce").dt.strftime("%Y-%m-%d")
    combined["symbol"] = combined["symbol"].map(normalize_symbol)
    combined = (
        combined[RUNTIME_COLUMNS]
        .dropna(subset=["date", "symbol", "close"])
        .sort_values(["date", "symbol"])
        .drop_duplicates(["date", "symbol"], keep="last")
        .reset_index(drop=True)
    )
    output_path = output_dir / "prices_long.csv"
    atomic_write_csv(combined, output_path)
    return {
        "path": str(output_path),
        "rows": int(len(combined)),
        "start_date": str(combined["date"].min()),
        "end_date": str(combined["date"].max()),
        "symbols": int(combined["symbol"].nunique()),
    }


def update_manifest(output_dir: Path, args: argparse.Namespace, universe: pd.DataFrame, records: list[dict], combined: dict | None) -> None:
    manifest_path = output_dir / "manifest.json"
    previous_manifest: dict = {}
    if manifest_path.exists():
        try:
            previous_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Failed to parse existing manifest %s: %s", manifest_path, exc)

    update_summary = {
        "updated_at": datetime.now().isoformat(timespec="seconds"),
        "schema": "akshare_strategy_runtime_ohlcv_v1",
        "update_type": "daily_incremental",
        "output_dir": str(output_dir),
        "end_date": args.end_date,
        "refresh_days": args.refresh_days,
        "adjust": args.adjust,
        "data_sources": parse_sources(args.data_sources),
        "universe_count": int(len(universe)),
        "updated_count": sum(1 for r in records if r["status"] == "updated"),
        "refreshed_count": sum(1 for r in records if r["status"] == "refreshed"),
        "no_new_data_count": sum(1 for r in records if r["status"] == "no_new_data"),
        "failed_count": sum(1 for r in records if r["status"] == "failed"),
        "combined": combined,
        "symbol_records": records,
    }
    manifest = {
        **previous_manifest,
        "schema": "akshare_strategy_runtime_ohlcv_v1",
        "columns": RUNTIME_COLUMNS,
        "latest_update": update_summary,
    }
    atomic_write_text(manifest_path, json.dumps(manifest, ensure_ascii=False, indent=2))


def run_update_once(args: argparse.Namespace) -> dict:
    output_dir = Path(args.output_dir)
    symbol_dir = output_dir / "symbols"
    symbol_dir.mkdir(parents=True, exist_ok=True)
    data_sources = parse_sources(args.data_sources)

    if args.skip_non_trading_day and not is_trading_day(args.end_date, data_sources, args.adjust, args.trading_day_check):
        summary = {
            "status": "skipped_non_trading_day",
            "end_date": args.end_date,
            "updated": 0,
            "refreshed": 0,
            "no_new": 0,
            "failed": 0,
            "failed_ratio": 0.0,
        }
        LOGGER.info("Skip update because %s is not an A-share trading day.", args.end_date)
        return summary

    lock_file = Path(args.lock_file) if args.lock_file else output_dir / ".daily_update.lock"
    with exclusive_lock(lock_file, stale_seconds=args.lock_stale_seconds) as acquired:
        if not acquired:
            return {
                "status": "skipped_locked",
                "end_date": args.end_date,
                "updated": 0,
                "refreshed": 0,
                "no_new": 0,
                "failed": 0,
                "failed_ratio": 0.0,
            }

        if args.refresh_universe:
            universe = refresh_universe(
                output_dir=output_dir,
                date=args.end_date,
                data_sources=data_sources,
                include_chinext=args.include_chinext,
                include_star=args.include_star,
                include_bse=args.include_bse,
                include_st=args.include_st,
                limit=args.limit,
            )
        else:
            universe = load_existing_universe(output_dir)
            if args.limit:
                universe = universe.head(args.limit)

        LOGGER.info(
            "Start daily update: output=%s symbols=%s end_date=%s refresh_days=%s sources=%s dry_run=%s workers=%s",
            output_dir,
            len(universe),
            args.end_date,
            args.refresh_days,
            ",".join(data_sources),
            args.dry_run,
            args.workers,
        )

        tasks = [
            (index, normalize_symbol(row["symbol"]))
            for index, row in enumerate(universe.to_dict("records"), start=1)
        ]
        records: list[dict] = []
        if args.workers <= 1:
            for index, symbol in tasks:
                records.append(
                    update_symbol_with_retries(
                        index=index,
                        total=len(tasks),
                        symbol=symbol,
                        symbol_dir=symbol_dir,
                        args=args,
                        data_sources=data_sources,
                    )
                )
        else:
            with ThreadPoolExecutor(max_workers=args.workers) as executor:
                futures = [
                    executor.submit(
                        update_symbol_with_retries,
                        index=index,
                        total=len(tasks),
                        symbol=symbol,
                        symbol_dir=symbol_dir,
                        args=args,
                        data_sources=data_sources,
                    )
                    for index, symbol in tasks
                ]
                for completed, future in enumerate(as_completed(futures), start=1):
                    records.append(future.result())
                    if completed % max(1, args.workers * 5) == 0 or completed == len(futures):
                        LOGGER.info("Completed %s/%s symbol updates", completed, len(futures))
            records = sorted(records, key=lambda item: item.get("index", 0))

        combined = None
        if not args.no_combined and not args.dry_run:
            LOGGER.info("Rebuild prices_long.csv")
            combined = rebuild_prices_long(output_dir)

        if not args.dry_run:
            update_manifest(output_dir, args, universe, records, combined)

        updated = sum(1 for r in records if r["status"] == "updated")
        refreshed = sum(1 for r in records if r["status"] == "refreshed")
        no_new = sum(1 for r in records if r["status"] == "no_new_data")
        failed = sum(1 for r in records if r["status"] == "failed")
        failed_ratio = failed / len(records) if records else 0.0
        successful_responses = updated + refreshed
        no_effective_response = len(records) > 0 and successful_responses == 0
        summary = {
            "status": "failed" if failed_ratio > args.max_failed_ratio or no_effective_response else "success",
            "end_date": args.end_date,
            "updated": updated,
            "refreshed": refreshed,
            "no_new": no_new,
            "failed": failed,
            "failed_ratio": failed_ratio,
            "combined": combined,
        }
        LOGGER.info(
            "Finished daily update: updated=%s refreshed=%s no_new=%s failed=%s failed_ratio=%.2f%%",
            updated,
            refreshed,
            no_new,
            failed,
            failed_ratio * 100,
        )
        if no_effective_response:
            raise RuntimeError("Daily update received no effective symbol responses; possible network or data-source outage.")
        if summary["status"] == "failed":
            raise RuntimeError(
                f"Daily update failure ratio {failed_ratio:.2%} exceeds threshold {args.max_failed_ratio:.2%}"
            )
        return summary


def seconds_until_run_at(run_at: str, now: pd.Timestamp | None = None) -> float:
    now = now or pd.Timestamp.now()
    hour_text, minute_text = run_at.split(":", maxsplit=1)
    target = now.normalize() + pd.Timedelta(hours=int(hour_text), minutes=int(minute_text))
    if target <= now:
        target += pd.Timedelta(days=1)
    return max(0.0, float((target - now).total_seconds()))


def should_run_today(run_at: str, last_run_date: str | None, now: pd.Timestamp | None = None) -> bool:
    now = now or pd.Timestamp.now()
    hour_text, minute_text = run_at.split(":", maxsplit=1)
    today = yyyymmdd(now.normalize())
    target = now.normalize() + pd.Timedelta(hours=int(hour_text), minutes=int(minute_text))
    return now >= target and last_run_date != today


def run_daemon(args: argparse.Namespace) -> None:
    scheduler_state_file = Path(args.scheduler_state_file)
    scheduler_state = load_json_file(scheduler_state_file)
    last_run_date = scheduler_state.get("last_run_date")
    LOGGER.info(
        "Start scheduler daemon: run_at=%s output=%s last_run_date=%s",
        args.run_at,
        args.output_dir,
        last_run_date,
    )
    while True:
        now = pd.Timestamp.now()
        if should_run_today(args.run_at, last_run_date, now):
            args.end_date = yyyymmdd(now.normalize())
            try:
                summary = run_update_once(args)
                LOGGER.info("Scheduled update summary: %s", summary)
                notify_feishu(args, summary)
            except Exception as exc:  # noqa: BLE001
                message = f"Scheduled daily update failed for {args.end_date}: {exc}"
                LOGGER.exception(message)
                summary = {
                    "status": "failed",
                    "end_date": args.end_date,
                    "updated": 0,
                    "refreshed": 0,
                    "no_new": 0,
                    "failed": 0,
                    "failed_ratio": 1.0,
                }
                notify_feishu(
                    args,
                    summary,
                )
                run_alert(args.alert_command, status="failed", message=message, output_dir=Path(args.output_dir))
            finally:
                update_scheduler_state(
                    scheduler_state_file,
                    target_date=args.end_date,
                    status=summary.get("status", "unknown"),
                )
                last_run_date = args.end_date
            time.sleep(60)
            continue

        sleep_seconds = min(seconds_until_run_at(args.run_at, now), 300.0)
        LOGGER.info("Next update check in %.0f seconds; run_at=%s", sleep_seconds, args.run_at)
        time.sleep(max(60.0, sleep_seconds))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Daily incremental updater for offline A-share OHLCV data.")
    parser.add_argument(
        "--output-dir",
        default="/Users/bytedance/cqm/Personal_Strategy/data/offline/a_share_12m_tencent_sina",
        help="Existing offline dataset directory to update.",
    )
    parser.add_argument("--end-date", default=yyyymmdd(pd.Timestamp.today().normalize()), help="Update through YYYYMMDD. Default: today.")
    parser.add_argument("--refresh-days", type=int, default=10, help="Re-fetch this many calendar days before each symbol's latest date.")
    parser.add_argument("--adjust", default="qfq", choices=["", "qfq", "hfq"], help="Price adjustment. Default: qfq.")
    parser.add_argument("--data-sources", default="tencent,sina", help="Comma-separated data sources in fallback order.")
    parser.add_argument("--sleep-seconds", type=float, default=0.15, help="Sleep between symbol requests.")
    parser.add_argument("--limit", type=int, help="Limit symbols for smoke testing.")
    parser.add_argument("--refresh-universe", action="store_true", help="Refresh universe.csv before updating symbols.")
    parser.add_argument("--include-chinext", action="store_true", help="Include ChiNext 300/301 stocks when refreshing universe.")
    parser.add_argument("--include-star", action="store_true", help="Include STAR 688/689 stocks when refreshing universe.")
    parser.add_argument("--include-bse", action="store_true", help="Include BSE 4/8/920 stocks when refreshing universe.")
    parser.add_argument("--include-st", action="store_true", help="Include ST/*ST stocks when refreshing universe.")
    parser.add_argument("--trim-before", help="Optional YYYYMMDD/ISO date; drop rows before this date from per-symbol files.")
    parser.add_argument("--no-combined", action="store_true", help="Do not rebuild prices_long.csv.")
    parser.add_argument("--dry-run", action="store_true", help="Fetch and merge in memory without writing files.")
    parser.add_argument("--daemon", action="store_true", help="Run continuously and execute once per day at --run-at.")
    parser.add_argument("--run-at", default="16:30", help="Daily local time HH:MM used with --daemon. Default: 16:30.")
    parser.add_argument("--scheduler-state-file", default=str(DEFAULT_SCHEDULER_STATE_FILE), help="Local state file for daemon run deduplication.")
    parser.add_argument("--skip-non-trading-day", action=argparse.BooleanOptionalAction, default=True, help="Skip when --end-date is not an A-share trading day.")
    parser.add_argument("--trading-day-check", choices=["auto", "weekday", "off"], default="auto", help="Trading day check mode. auto verifies 000001 has a daily bar.")
    parser.add_argument("--lock-file", help="Optional lock file path. Default: <output-dir>/.daily_update.lock")
    parser.add_argument("--lock-stale-seconds", type=int, default=6 * 3600, help="Only used for stale lock logging. OS lock still wins.")
    parser.add_argument("--workers", type=int, default=8, help="Concurrent symbol update workers. Use 1 for sequential mode.")
    parser.add_argument("--retries", type=int, default=2, help="Retries per symbol after exceptions.")
    parser.add_argument("--retry-sleep-seconds", type=float, default=3.0, help="Sleep between symbol retries.")
    parser.add_argument("--max-failed-ratio", type=float, default=0.05, help="Fail the run if failed symbols exceed this ratio.")
    parser.add_argument("--log-file", default="logs/offline_daily_update.log", help="Append logs to this file.")
    parser.add_argument("--alert-command", help="Shell command executed on run failure. Env: UPDATE_STATUS, UPDATE_MESSAGE, UPDATE_OUTPUT_DIR.")
    parser.add_argument("--feishu-notify", action=argparse.BooleanOptionalAction, default=True, help="Send run summary to Feishu bot.")
    parser.add_argument("--feishu-notify-dry-run", action="store_true", help="Also send Feishu notification during dry-run.")
    parser.add_argument("--feishu-webhook-file", default="/Users/bytedance/cqm/Personal_Strategy/.feishu_webhook", help="Local file containing Feishu/Lark bot webhook URL.")
    parser.add_argument("--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    setup_logging(args.log_level, args.log_file)
    try:
        if args.daemon:
            run_daemon(args)
        else:
            summary = run_update_once(args)
            LOGGER.info("Update summary: %s", summary)
            notify_feishu(args, summary)
    except Exception as exc:  # noqa: BLE001
        message = f"Daily update failed for {args.end_date}: {exc}"
        LOGGER.exception(message)
        notify_feishu(
            args,
            {
                "status": "failed",
                "end_date": args.end_date,
                "updated": 0,
                "refreshed": 0,
                "no_new": 0,
                "failed": 0,
                "failed_ratio": 1.0,
            },
        )
        run_alert(args.alert_command, status="failed", message=message, output_dir=Path(args.output_dir))
        sys.exit(1)


if __name__ == "__main__":
    main()
